### ISSUE TITLE
src/app/minerdetails/

### ISSUE THREAD

**Issue by suhabe** [neu-info7500-spring-04/bitcoin-explorer#64]
Is it possible to remove `graphqlClientWithConstantBase` and instead replace it with the normal client `graphqlClient`? There's shouldn't be a need to explicitly invoke the nextjs server -- the intent of SSR is to have the interaction be transparent.

I've commented out this component from the top level page for now.

**Comment by rohitpanicker06** [comment]
Sure, I'll work on this.
