### ISSUE TITLE
TransactionFeesChart

### ISSUE THREAD

**Issue by suhabe** [neu-info7500-spring-04/bitcoin-explorer#65]
The TransactionFeesChart is causing warnings to show up in the console logs of the web browser.
Let's fix those warnings -- console of the browser should stay clean/empty so when problems to do happen, we can easily spot them in the logs.

I've commented out TransactionFeesChart from the top level page until the warnings are fixed.

**Comment by RuolinLi06** [comment]
To solve the issue of warnings caused by rechart not being compatible, I've switched to using the echart. Updated in PR #69 .
